services:
  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=${AUTH_DATABASE_URL}
    depends_on:
      - redis
  profile:
    build:
      context: .
      dockerfile: services/profile/Dockerfile
    ports:
      - "4001:4001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  journal:
    build:
      context: .
      dockerfile: services/journal/Dockerfile
    ports:
      - "4002:4002"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: